#!/usr/bin/env php
<?php

# Usage :
#
#   $ sudo blinker 17 200000
#
# = Blink GPIO #17 pin with 0.2 second delay

require 'vendor/autoload.php';

use PhpGpio\Gpio;

// Am i using php-cli?
if ('cli' != PHP_SAPI) {
    echo $msg = "This script must be run using php-cli";
    throw new \Exception($msg);
}

// Am I a sudoer or the root user?
if ('root' !== $_SERVER['USER'] || empty($_SERVER['SUDO_USER'])) {
    echo $msg = "Please run this script as root, using sudo -t ; please check the README file";
    throw new \Exception($msg);
}

// Am I using only 2 integer arguments ?
if (
    !(2 === $argc)
    || strlen($argv[1]) > 300
) {
    echo $msg = "Blä";
    throw new \Exception($msg);
}

$str = mb_strtoupper($argv[1]);
$inputs = preg_split('/(?<!^)(?!$)/u', $str);
$gpio = new GPIO();

$map = array(
  1 => 13,
  2 => 6,
  3 => 17,
  4 => 22,
  5 => 27,
  6 => 19,
  7 => 26
);

$segments = array(
  ' ' => array(),
  '.' => array(3),
  ',' => array(3),
  '-' => array(7),
  '0' => array(1,2,3,4,5,6),
  '1' => array(5,6),
  '2' => array(1,2,4,5,7),
  '3' => array(1,2,3,4,7),
  '4' => array(2,3,6,7),
  '5' => array(1,3,4,6,7),
  '6' => array(1,3,4,5,6,7),
  '7' => array(1,2,3),
  '8' => array(1,2,3,4,5,6,7),
  '9' => array(1,2,3,4,6,7),
  'A' => array(1,2,3,5,6,7),
  'B' => array(3,4,5,6,7),
  'C' => array(4,5,7),
  'D' => array(2,3,4,5,7),
  'E' => array(1,4,5,6,7),
  'F' => array(1,5,6,7),
  'G' => array(1,3,4,5,6),
  'H' => array(3,5,6,7),
  'I' => array(5,6),
  'J' => array(2,3,4,5),
  'K' => array(2,3,5,6,7),
  'L' => array(4,5,6),
  'M' => array(1,4,7),
  'N' => array(3,5,7),
  'O' => array(3,4,5,7),
  'P' => array(1,2,5,6,7),
  'Q' => array(1,2,3,6,7),
  'R' => array(5,7),
  'S' => array(1,3,4,6,7),
  'T' => array(4,5,6,7),
  'U' => array(3,4,5),
  'V' => array(1,2,3,4,5),
  'W' => array(1,2,6),
  'X' => array(2,3,5,6,7),
  'Y' => array(2,3,6,7),
  'Z' => array(1,2,4,5,7),
  'Å' => array(1,2,3,5,6,7),
  'Ä' => array(1,2,3,5,6,7),
  'Ö' => array(1,3,4,5,7),
  'å' => array(1,2,3,5,6,7),
  'ä' => array(1,2,3,5,6,7),
  'ö' => array(1,3,4,5,7),
);

foreach ($inputs as $input) {
  echo "$input\n";
  foreach ($segments[$input] as $segment) {
    $pin = $map[$segment];
    $gpio->setup($pin, "out");
    $gpio->output($pin, 1);
  }

  usleep('500000');

  foreach ($segments[$input] as $segment) {
    $pin = $map[$segment];
    $gpio->output($pin, 0);
  }

  usleep('10000');
}


$gpio->unexportAll();

